services:
  api:
    build: .
    ports:
      - "80:80"
    command:
      - /bin/bash
      - -c
      - |
        python cakeshop/initiate_db.py
        uvicorn cakeshop.main:app --host 0.0.0.0 --port 80
  test-api:
    build: .
    command:
      - /bin/bash
      - -c
      - |
        pytest -rA
